%% generate_methods_doc.m
% Generates a Word document describing the 6D-SMOLM tracking methodology.
% Uses COM automation (ActiveX) to control Microsoft Word directly.
%
% Equations use Word's Unicode linear math format (NOT LaTeX).
% Key differences from LaTeX:
%   - Accents are POSTFIX: type char then combining accent (e.g., x followed by U+0302 for hat)
%   - Greek letters: use actual Unicode chars directly
%   - Fractions: (numerator)/(denominator)
%   - Subscripts: base_(sub) for multi-char subscripts
%   - No backslash commands
%
% Usage: run this script from the software6D/docs/ folder.
% Requires: Microsoft Word installed on Windows.

finalFile = fullfile(pwd, '6DSMOLM_tracking_methods.docx');
% Use a temp path outside OneDrive for COM operations
outputFileWin = fullfile(tempdir, '6DSMOLM_tracking_methods.docx');

%% ---- Unicode constants ----
% Greek letters
theta   = char(952);   % θ
phi_ch  = char(966);   % φ
psi_ch  = char(968);   % ψ
omega_ch= char(937);   % Ω (capital Omega — wobble angle)
alpha_ch= char(945);   % α
gamma_ch= char(947);   % γ
sigma_ch= char(963);   % σ
mu_ch   = char(956);   % μ
delta_ch= char(916);   % Δ (uppercase)
pi_ch   = char(960);   % π
tau_ch  = char(964);   % τ
% Math symbols
hat     = char(770);   % combining circumflex accent U+0302
cdot    = char(8901);  % ⋅
cross_ch= char(215);   % ×
sup2    = char(178);   % ²
langle  = char(10216); % ⟨
rangle  = char(10217); % ⟩
sqrt_ch = char(8730);  % √
leq     = char(8804);  % ≤
infty   = char(8734);  % ∞
approx  = char(8776);  % ≈
rightarrow = char(8594); % →

%% ---- Open Word via COM ----
word = actxserver('Word.Application');
word.Visible = false;
wdoc = word.Documents.Add;

% Page setup (72 points = 1 inch)
sec = wdoc.Sections.Item(1);
sec.PageSetup.TopMargin = 72;
sec.PageSetup.BottomMargin = 72;
sec.PageSetup.LeftMargin = 72;
sec.PageSetup.RightMargin = 72;

sel = word.Selection;

%% ---- Helper functions ----
    function writeHeading(sel, text, level)
        sel.Style = ['Heading ' num2str(level)];
        sel.Font.Name = 'Times New Roman';
        sel.Font.Bold = true;
        sel.Font.Italic = false;
        sel.Font.set('Color', 0); % black
        if level == 1
            sel.Font.Size = 14;
        elseif level == 2
            sel.Font.Size = 12;
        end
        sel.TypeText(text);
        sel.TypeParagraph;
    end

    function writeBody(sel, text)
        sel.Style = 'Normal';
        sel.Font.Name = 'Times New Roman';
        sel.Font.Size = 11;
        sel.Font.Bold = false;
        sel.Font.Italic = false;
        sel.Font.set('Color', 0); % black
        sel.ParagraphFormat.Alignment = 0; % wdAlignParagraphLeft
        sel.ParagraphFormat.SpaceAfter = 6;
        sel.ParagraphFormat.LineSpacingRule = 5; % wdLineSpaceMultiple
        sel.ParagraphFormat.LineSpacing = 14.4; % ~1.15 spacing
        sel.TypeText(text);
        sel.TypeParagraph;
    end

    function writeBodyAuto(sel, wordDoc, txt)
        % Body paragraph with inline math. Wrap math segments in $...$.
        % Each $...$ becomes an inline OMath equation field.
        sel.Style = 'Normal';
        sel.ParagraphFormat.Alignment = 0;
        sel.ParagraphFormat.SpaceAfter = 6;
        sel.ParagraphFormat.LineSpacingRule = 5;
        sel.ParagraphFormat.LineSpacing = 14.4;
        parts = regexp(txt, '\$([^\$]*)\$', 'split');
        maths = regexp(txt, '\$([^\$]*)\$', 'tokens');
        for kk = 1:length(parts)
            sel.Font.Name = 'Times New Roman';
            sel.Font.Size = 11;
            sel.Font.Italic = false;
            sel.Font.Bold = false;
            sel.Font.set('Color', 0);
            if ~isempty(parts{kk})
                sel.TypeText(parts{kk});
            end
            if kk <= length(maths)
                mtxt = maths{kk}{1};
                sel.Font.Name = 'Cambria Math';
                sel.Font.Italic = true;
                sel.Font.set('Color', 0);
                startPos = sel.Range.Start;
                sel.TypeText(mtxt);
                endPos = sel.Range.Start;
                try
                    eqRange = wordDoc.Range(startPos, endPos);
                    om = wordDoc.OMaths.Add(eqRange);
                    om.Type = 1; % wdOMathInline
                catch ME
                    fprintf('  Inline math warning: %s\n', ME.message);
                end
                sel.EndKey(6); % wdStory
            end
        end
        sel.TypeParagraph;
    end

    function writeEquation(sel, wordDoc, eqText)
        % Insert equation using Word's OMML via COM.
        % eqText should be in Word's Unicode linear math format.
        sel.Style = 'Normal';
        sel.ParagraphFormat.Alignment = 1; % wdAlignParagraphCenter
        sel.ParagraphFormat.SpaceAfter = 2;
        sel.ParagraphFormat.SpaceBefore = 6;
        sel.Font.Name = 'Cambria Math';
        sel.Font.Size = 11;
        sel.Font.Italic = true;
        sel.Font.set('Color', 0); % black
        startPos = sel.Range.Start;
        sel.TypeText(eqText);
        endPos = sel.Range.Start;
        try
            eqRange = wordDoc.Range(startPos, endPos);
            omath = wordDoc.OMaths.Add(eqRange);
        catch ME
            fprintf('  Equation warning (Add): %s\n', ME.message);
        end
        sel.EndKey(6); % wdStory
        sel.TypeParagraph;
    end

    function writeCodeRef(sel, refText)
        % Write a code location reference in small gray italic text
        % Word COM Color uses BGR format: R + G*256 + B*256^2
        sel.Style = 'Normal';
        sel.ParagraphFormat.Alignment = 1; % wdAlignParagraphCenter
        sel.ParagraphFormat.SpaceAfter = 6;
        sel.ParagraphFormat.SpaceBefore = 0;
        sel.Font.Name = 'Consolas';
        sel.Font.Size = 8;
        sel.Font.Italic = true;
        sel.Font.Bold = false;
        sel.Font.set('Color', 128 + 128*256 + 128*65536); % Gray (RGB 128,128,128)
        sel.TypeText(['Code: ' refText]);
        sel.TypeParagraph;
        % Reset font color to black
        sel.Font.set('Color', 0); % Black
    end

    function writeRef(sel, num, text)
        % Write a numbered reference entry
        sel.Style = 'Normal';
        sel.Font.Name = 'Times New Roman';
        sel.Font.Size = 10;
        sel.Font.Bold = false;
        sel.Font.Italic = false;
        sel.ParagraphFormat.Alignment = 0;
        sel.ParagraphFormat.SpaceAfter = 4;
        sel.ParagraphFormat.LeftIndent = 28; % hanging indent
        sel.ParagraphFormat.FirstLineIndent = -28;
        sel.Font.set('Color', 0);
        sel.TypeText(['[' num2str(num) '] ' text]);
        sel.TypeParagraph;
        sel.ParagraphFormat.LeftIndent = 0;
        sel.ParagraphFormat.FirstLineIndent = 0;
    end

%% ========================================================================
%  DOCUMENT CONTENT
%% ========================================================================

%% Title
sel.Style = 'Title';
sel.Font.Name = 'Times New Roman';
sel.Font.Bold = true;
sel.Font.set('Color', 0);
sel.Font.Size = 16;
sel.ParagraphFormat.Alignment = 1;
sel.TypeText('Orientation-Augmented Single-Molecule Tracking via 6D-SMOLM Cost Function Integration within u-track3D');
sel.TypeParagraph;

% Author
sel.Style = 'Normal';
sel.Font.Name = 'Times New Roman';
sel.Font.Bold = false;
sel.Font.set('Color', 0);
sel.Font.Size = 11;
sel.ParagraphFormat.Alignment = 1;
sel.ParagraphFormat.SpaceAfter = 12;
sel.TypeText('Emil Gillett, Landes Research Group, University of Illinois Urbana-Champaign');
sel.TypeParagraph;

%% ---- ABSTRACT ----
writeHeading(sel, 'Abstract', 1);

writeBody(sel, ...
    ['Single-molecule orientation tracking requires joint optimization of spatial and angular coordinates, ' ...
    'a capability absent from existing particle tracking frameworks. ' ...
    'We present a wrapping strategy that extends u-track3D [1] with orientation-aware cost functions ' ...
    'for the linear assignment problem (LAP), enabling six-dimensional single-molecule orientation localization microscopy (6D-SMOLM) tracking. ' ...
    'The implementation preserves the validated spatial Kalman filter [2] of u-track3D while augmenting the linking and gap-closing cost matrices ' ...
    'with angular distance terms derived from rotational Brownian dynamics on the unit sphere. ' ...
    'Three orientation motion models compete at each linking step, and per-track rotational diffusion coefficients are learned adaptively from track history. ' ...
    'Fluorophore photophysics are modeled as a three-state Markov process to generate realistic temporal gaps for benchmarking gap-closing performance [8,9]. ' ...
    'This approach resolves linking ambiguities that purely spatial tracking cannot, ' ...
    'particularly in dense fields where molecules with distinct orientations occupy similar spatial positions (Figure 2).']);

%% ---- 1. SOFTWARE ARCHITECTURE ----
writeHeading(sel, '1. Introduction and Software Architecture', 1);

writeBody(sel, ...
    ['The 6D-SMOLM tracking pipeline extends u-track3D through a wrapper architecture that preserves the original spatial tracking engine ' ...
    'while injecting orientation information into the cost matrices. ' ...
    'In u-track3D, two sequential linear assignment problems (LAPs) govern track construction [1]: ' ...
    'LAP 1 performs frame-to-frame linking by optimizing assignments between detections in consecutive frames, ' ...
    'and LAP 2 closes gaps, merges, and splits track segments across multiple frames (Figure 2). ' ...
    'Our wrapper functions, costMat6DSMOLMLink and costMat6DSMOLMCloseGaps, first call the original u-track3D cost functions ' ...
    '(costMatRandomDirectedSwitchingMotionLink and costMatRandomDirectedSwitchingMotionCloseGaps) to obtain baseline spatial cost matrices, ' ...
    'then augment each valid cost entry with an additive orientation penalty. ' ...
    'This strategy ensures that the spatial Kalman filter state propagation, nearest-neighbor distance computation, ' ...
    'and all other internal u-track3D bookkeeping remain unmodified, ' ...
    'isolating orientation logic to the cost function layer alone.']);

writeBodyAuto(sel, wdoc, ...
    ['Each 6D-SMOLM localization provides six coordinates: three spatial $(x, y, z)$ and three orientational $(' ...
    theta ', ' phi_ch ', ' omega_ch ')$. ' ...
    'The polar angle $' theta '$ and azimuthal angle $' phi_ch '$ define the mean dipole orientation unit vector on the upper hemisphere, ' ...
    'while the wobble angle $' omega_ch '$ quantifies the solid angle subtended by orientational fluctuations during the camera exposure [3]. ' ...
    'The spatial coordinates enter the cost matrix through u-track3D''s existing Kalman filter machinery, ' ...
    'while $' theta '$ and $' phi_ch '$ enter through our orientation cost term. ' ...
    'The wobble angle $' omega_ch '$ serves a dual role: it contributes an optional independent cost term ' ...
    'and modulates the measurement noise assigned to $' theta '$ and $' phi_ch '$, ' ...
    'since higher wobble degrades the precision of instantaneous orientation estimates [4].']);

%% ---- 2. SPATIAL KALMAN FILTER ----
writeHeading(sel, '2. Spatial Tracking via Kalman Filtering', 1);

rh = ['r' hat];

writeBodyAuto(sel, wdoc, ...
    ['The u-track3D Kalman filter provides optimal position predictions by recursively estimating particle state vectors from noisy localizations [2]. ' ...
    'For each tracked particle, the state vector $' rh '$ contains position and velocity components in each spatial dimension. ' ...
    'For example, in three dimensions $' rh '=(x, v_x, y, v_y, z, v_z)$, ' ...
    'where $x$, $y$, $z$ are the spatial coordinates and $v_x$, $v_y$, $v_z$ are the corresponding velocities. ' ...
    'The notation $' rh '(t|t-1)$ reads "the estimate of $' rh '$ at frame $t$, given all observations through frame $t-1$"; ' ...
    'the vertical bar means "given" and separates the time being estimated from the last time data was available.']);

writeBodyAuto(sel, wdoc, ...
    ['At each frame transition, the filter predicts where the particle will be in the next frame ' ...
    'by propagating the current state estimate forward through a linear motion model. ' ...
    'The state prediction equation is:']);

writeEquation(sel, wdoc, [rh '(t|t-1)=F' cdot rh '(t-1|t-1)']);
writeCodeRef(sel, 'costMatRandomDirectedSwitchingMotionLink.m:217');

writeBodyAuto(sel, wdoc, ...
    ['This equation multiplies the previous state estimate $' rh '(t-1|t-1)$ by the state transition matrix $F$ ' ...
    'to obtain a predicted state $' rh '(t|t-1)$ for the current frame. ' ...
    'The matrix $F$ encodes the assumed motion model; for constant-velocity motion, ' ...
    '$F$ propagates positions forward by adding velocity times the frame interval. ' ...
    'The variable $t$ denotes the current frame index and $t-1$ the previous frame.']);

writeBodyAuto(sel, wdoc, ...
    ['Along with the state prediction, the filter must also predict how its uncertainty grows over time. ' ...
    'The state covariance matrix $P$ quantifies the uncertainty in the state estimate: ' ...
    'larger values of $P$ indicate less confidence in the predicted position. ' ...
    'The covariance prediction equation is:']);

writeEquation(sel, wdoc, ['P(t|t-1)=F' cdot 'P(t-1|t-1)' cdot 'F^T+Q']);
writeCodeRef(sel, 'costMatRandomDirectedSwitchingMotionLink.m:220-221');

writeBodyAuto(sel, wdoc, ...
    ['This equation propagates the previous covariance $P(t-1|t-1)$ through the motion model $F$, ' ...
    'then adds the process noise covariance $Q$. ' ...
    'The superscript $T$ denotes the matrix transpose. ' ...
    'The transpose appears because covariance matrices transform as $F' cdot 'P' cdot 'F^T$ under a linear operation $F$, ' ...
    'a standard result from linear algebra [2]. ' ...
    'The matrix $Q$ represents the random component of particle motion between frames: ' ...
    'even a perfect position estimate becomes less certain after one frame because the particle moves stochastically.']);

writeBodyAuto(sel, wdoc, ...
    ['u-track3D evaluates multiple competing motion models (e.g., Brownian, directed, switching), ' ...
    'each with its own transition matrix $F$. ' ...
    'The prediction step is performed under each model, and the model yielding the lowest cost ' ...
    'for a given track-detection pair is selected [1].']);

writeHeading(sel, '2.1 Innovation and Kalman Gain', 2);

writeBodyAuto(sel, wdoc, ...
    ['After predicting the state, the filter compares the prediction to the actual measurement. ' ...
    'The innovation (or residual) $y$ is the difference between the observed detection position $m$ ' ...
    'and the predicted observation. We use the symbol $m$ (for "measurement") rather than $z$, ' ...
    'because $z$ is already reserved for the axial spatial coordinate of the dipole.']);

writeEquation(sel, wdoc, ['y=m-H' cdot rh '(t|t-1)']);
writeCodeRef(sel, 'kalmanGainLinearMotion.m:158');

writeBodyAuto(sel, wdoc, ...
    ['Here $m$ is the measured position vector of the candidate detection, ' ...
    'and $H$ is the observation matrix that extracts the position components from the full state vector ' ...
    '(since $' rh '$ contains both positions and velocities, but $m$ contains only positions). ' ...
    'The product $H' cdot rh '(t|t-1)$ gives the predicted position in measurement space.']);

writeBodyAuto(sel, wdoc, ...
    ['The innovation covariance $S$ quantifies the total uncertainty in the innovation, ' ...
    'combining the prediction uncertainty with the measurement noise:']);

writeEquation(sel, wdoc, ['S=H' cdot 'P(t|t-1)' cdot 'H^T+R']);
writeCodeRef(sel, 'kalmanGainLinearMotion.m:149-151');

writeBodyAuto(sel, wdoc, ...
    ['The matrix $R$ is the measurement noise covariance, constructed from the squared localization uncertainties ' ...
    'reported for each detection. ' ...
    'The Kalman gain $K$, which determines how much the filter trusts the new measurement versus its prediction, is:']);

writeEquation(sel, wdoc, ['K=P(t|t-1)' cdot 'H^T' cdot 'S^(-1)']);
writeCodeRef(sel, 'kalmanGainLinearMotion.m:149-151');

writeBodyAuto(sel, wdoc, ...
    ['The Kalman gain $K$ weights the innovation $y$ to produce a correction $K' cdot 'y$ ' ...
    'that is applied to the predicted state. ' ...
    'When the prediction uncertainty $P$ is large relative to the measurement noise $R$, ' ...
    'the gain is large and the filter trusts the measurement. ' ...
    'When $P$ is small relative to $R$, the gain is small and the filter trusts its prediction.']);

writeHeading(sel, '2.2 Spatial Linking Cost', 2);

writeBody(sel, ...
    ['The spatial linking cost between a predicted track position and a candidate detection ' ...
    'is the squared Euclidean distance between the predicted observation and the measured position [1]:']);

writeEquation(sel, wdoc, ['C_(spatial)(i,j)=||m_j-H' cdot rh '_i(t|t-1)||^2']);
writeCodeRef(sel, 'costMatRandomDirectedSwitchingMotionLink.m:249,301');

writeBodyAuto(sel, wdoc, ...
    ['Here $i$ indexes the track and $j$ indexes the candidate detection. ' ...
    'The cost is computed for each combination of motion model (propagation scheme), ' ...
    'and the minimum cost across all models is retained. ' ...
    'This is a Euclidean distance squared, not normalized by the innovation covariance $S$.']);

writeBodyAuto(sel, wdoc, ...
    ['The Kalman filter''s uncertainty enters the cost matrix indirectly through a search radius gate. ' ...
    'For each track, the search radius is proportional to the Kalman standard deviation ' ...
    '$' sqrt_ch '(P)$, multiplied by a user-specified factor (brownStdMult, default: 3). ' ...
    'The search radius may be expanded based on local particle density, ' ...
    'but is clamped between user-specified minimum and maximum values. ' ...
    'Track-detection pairs whose distance exceeds the search radius are excluded from the cost matrix ' ...
    'by setting their cost to infinity (nonlinkMarker) [1]. ' ...
    'The remaining valid entries are then solved by the Jonker-Volgenant algorithm [7] ' ...
    'to obtain the globally optimal frame-to-frame assignment.']);

%% ---- 3. ORIENTATION COST: LEVEL 3 ----
writeHeading(sel, '3. Orientation Cost Function: Adaptive Three-Model Kalman (Level 3)', 1);

writeHeading(sel, '3.1 Angular Distance with Dipole Symmetry', 2);

writeBodyAuto(sel, wdoc, ...
    ['The angular distance between two dipole orientations must respect the head-tail symmetry inherent to fluorescent dipole emitters [3,4]. ' ...
    'A fluorescent dipole oriented at angles $(' theta ', ' phi_ch ')$ is physically indistinguishable from one at ' ...
    '$(' pi_ch '-' theta ', ' phi_ch '+' pi_ch ')$, ' ...
    'producing identical emission patterns in single-molecule imaging. ' ...
    'To enforce this symmetry, we convert the spherical angles to unit vectors on the upper hemisphere ' ...
    'and define the angular distance through the absolute value of their dot product:']);

muh = [mu_ch hat];
kh = ['k' hat];
writeEquation(sel, wdoc, [muh '=(sin' theta ' cos' phi_ch ',  sin' theta ' sin' phi_ch ',  cos' theta ')']);
writeCodeRef(sel, 'costMat6DSMOLMLink.m:611  |  generate6DTrajectories.m:367-368');

writeEquation(sel, wdoc, [psi_ch '=arccos(|' muh '_1' cdot muh '_2|)']);
writeCodeRef(sel, 'costMat6DSMOLMLink.m:624-625  (computeAngularDistanceMatrix)');

writeBodyAuto(sel, wdoc, ...
    ['The resulting angular distance $' psi_ch '$ lies in the range $[0, ' pi_ch '/2]$, correctly identifying antipodal orientations as identical. ' ...
    'This is the fundamental distance metric used throughout the orientation cost computation.']);

writeHeading(sel, ['3.2 Rotational Brownian Dynamics on S' sup2], 2);

writeBodyAuto(sel, wdoc, ...
    ['The expected angular displacement of a freely rotating dipole follows from rotational Brownian dynamics on the unit sphere $S^2$ [5]. ' ...
    'On $S^2$, the orientation diffuses along two independent tangent-plane directions, ' ...
    'each contributing a variance of $2D_(rot) ' delta_ch 't$ per time step, where $D_(rot)$ is the rotational diffusion coefficient. ' ...
    'The total mean-squared angular displacement therefore involves two components:']);

writeEquation(sel, wdoc, ['E[' delta_ch psi_ch sup2 ']=4D_(rot) ' delta_ch 't']);
writeCodeRef(sel, 'costMat6DSMOLMLink.m:426,429  |  generate6DTrajectories.m:619,632');

writeBodyAuto(sel, wdoc, ...
    ['This factor of 4 (rather than 2) distinguishes rotational diffusion on $S^2$ from one-dimensional translational diffusion [5]. ' ...
    'It is the rotational analog of the well-known result that mean-squared displacement in $d$ dimensions equals $2dDt$. ' ...
    'In the trajectory generator, two independent Gaussian samples with $' sigma_ch '=' sqrt_ch '(2D_(rot)' delta_ch 't)$ are drawn ' ...
    'in the tangent plane at the current orientation, producing a net angular step whose squared magnitude has expectation $4D_(rot)' delta_ch 't$.']);

writeHeading(sel, '3.3 Three Competing Motion Models', 2);

writeBodyAuto(sel, wdoc, ...
    ['Level 3 orientation tracking evaluates three competing propagation schemes for each track-detection candidate pair $(i, j)$ ' ...
    'and selects the scheme yielding the lowest cost. ' ...
    'These three schemes are the rotational analog of the forward / backward / Brownian translational motion models in ' ...
    'u-track3D''s costMatRandomDirectedSwitchingMotionLink, which evaluates linear motion in three directions (forward along the velocity, ' ...
    'backward along the velocity, and pure Brownian) and likewise picks the minimum-cost scheme [1]. ' ...
    'Here, instead of translating positions by $' char(177) 'v' delta_ch 't$ or leaving them in place, we rotate the dipole orientation ' ...
    'by $' char(177) '|' char(969) '|' delta_ch 't$ about the learned angular-velocity axis, or leave it unchanged.']);

writeBodyAuto(sel, wdoc, ...
    ['Let $' muh '_i$ denote the current orientation of track $i$, and let $' char(969) '_i$ be its estimated angular-velocity vector ' ...
    '(extracted from the last two frames of track history via the Rodrigues axis-angle that rotates $' muh '_i(t-1)$ into $' muh '_i(t)$). ' ...
    'Define $' kh '_i=' char(969) '_i / |' char(969) '_i|$. The three predicted orientations for the next frame are:']);

writeEquation(sel, wdoc, [muh '_(fwd)=Rodrigues(' muh '_i, ' kh '_i, +|' char(969) '_i|)']);
writeCodeRef(sel, 'costMat6DSMOLMLink.m:448');

writeEquation(sel, wdoc, [muh '_(bwd)=Rodrigues(' muh '_i, ' kh '_i, -|' char(969) '_i|)']);
writeCodeRef(sel, 'costMat6DSMOLMLink.m:449');

writeEquation(sel, wdoc, [muh '_(brn)=' muh '_i']);
writeCodeRef(sel, 'costMat6DSMOLMLink.m:455');

writeBodyAuto(sel, wdoc, ...
    ['The forward scheme assumes the dipole continues tumbling in the same sense as in the previous interval; ' ...
    'the backward scheme assumes it reverses; the Brownian scheme assumes any apparent rotation is purely diffusive ' ...
    '(no preferred axis). All three schemes share the same predicted angular variance $S_' psi_ch '$ ' ...
    '(defined in Section 3.5 below): only the predicted mean $' muh '$ differs.']);

writeBody(sel, ...
    'Orientation propagation uses the Rodrigues rotation formula with the sign convention of Hofling and Straube [5]:');

writeEquation(sel, wdoc, [muh '_(rot)=' muh ' cos' alpha_ch '-(' kh cross_ch muh ')sin' alpha_ch '+' kh '(' kh cdot muh ')(1-cos' alpha_ch ')']);
writeCodeRef(sel, 'costMat6DSMOLMLink.m:738-740  (rotateVector)  |  generate6DTrajectories.m:700-702  (rodrigues_rotate)');

writeBodyAuto(sel, wdoc, ...
    ['Here $' kh '$ is the unit rotation axis and $' alpha_ch '$ is the rotation angle. ' ...
    'The negative sign on the cross-product term follows the convention used in the synthetic trajectory generator (generate6DTrajectories.m), ' ...
    'ensuring consistency between simulation and tracking. ' ...
    'The angular velocity is estimated from the last two frames of track history by computing the Rodrigues axis and angle ' ...
    'that rotate the previous orientation into the current one.']);

writeHeading(sel, '3.4 Per-Track D_(rot) Learning', 2);

writeBodyAuto(sel, wdoc, ...
    ['The rotational diffusion coefficient $D_(rot)$ is learned adaptively for each track from its angular displacement history. ' ...
    'This is the rotational analog of the noise-corrected mean-squared displacement (MSD) estimator routinely used to extract ' ...
    'translational diffusion coefficients from camera-based single-particle tracks [6,11]. ' ...
    'The derivation proceeds in three steps.']);

writeBodyAuto(sel, wdoc, ...
    ['Step 1: Decompose the observed angular step. For each consecutive pair of detections in a track, ' ...
    'the measured angular displacement $' delta_ch alpha_ch '$ between the two noisy dipole orientations decomposes into the true rotational step ' ...
    'plus two independent measurement-noise contributions $' char(949) '_t$ and $' char(949) '_(t+' delta_ch 't)$, one at each endpoint:']);

writeEquation(sel, wdoc, [delta_ch alpha_ch '_(obs)=' delta_ch alpha_ch '_(true)+' char(949) '_(t+' delta_ch 't)-' char(949) '_t']);

writeBodyAuto(sel, wdoc, ...
    ['Each per-detection angular noise $' char(949) '$ has variance $' sigma_ch '_' psi_ch '^2$, the orientational Cramer-Rao lower bound [4]. ' ...
    'Because the true step and the two noises are uncorrelated, variances add:']);

writeEquation(sel, wdoc, [langle delta_ch alpha_ch sup2 rangle '_(obs)=' langle delta_ch alpha_ch sup2 rangle '_(true)+2' sigma_ch '_' psi_ch sup2]);

writeBodyAuto(sel, wdoc, ...
    ['The factor of 2 reflects the fact that two independent noisy orientation measurements (one at each end of the step) ' ...
    'each contribute $' sigma_ch '_' psi_ch '^2$.']);

writeBodyAuto(sel, wdoc, ...
    ['Step 2: Substitute the rotational Brownian dynamics result. ' ...
    'From Section 3.2 (and the tangent-plane construction visualized in the Appendix), ' ...
    'the true mean-squared angular displacement on the unit sphere is:']);

writeEquation(sel, wdoc, [langle delta_ch alpha_ch sup2 rangle '_(true)=4D_(rot)' delta_ch 't']);

writeBodyAuto(sel, wdoc, ...
    'Combining with the previous equation gives:');

writeEquation(sel, wdoc, [langle delta_ch alpha_ch sup2 rangle '_(obs)=4D_(rot)' delta_ch 't+2' sigma_ch '_' psi_ch sup2]);

writeBodyAuto(sel, wdoc, ...
    'Step 3: Solve for $D_(rot)$. Rearranging gives the noise-corrected MSD estimator used in the code:');

writeEquation(sel, wdoc, ['D_(rot)=(' langle delta_ch alpha_ch sup2 rangle '-2' sigma_ch '_' psi_ch sup2 ')/(4' delta_ch 't)']);
writeCodeRef(sel, 'costMat6DSMOLMLink.m:322-323');

writeBodyAuto(sel, wdoc, ...
    ['This is structurally identical to the translational MSD estimator $D=(' langle delta_ch 'r^2' rangle '-2' sigma_ch '_(xy)^2)/(2d' delta_ch 't)$, ' ...
    'derived in Michalet (2010) for single-particle tracking with localization error [11], ' ...
    'with the substitutions $' sigma_ch '_(xy) ' rightarrow ' ' sigma_ch '_' psi_ch '$ and $2d' delta_ch 't ' rightarrow ' 4' delta_ch 't$ ' ...
    '(the 4 comes from the two tangent-plane degrees of freedom on $S^2$). ' ...
    'The estimated $D_(rot)$ is clamped to the range $[0.001, 10' cross_ch 'D_(rot,prior)]$ to prevent divergence from noisy short tracks, ' ...
    'where $D_(rot,prior)$ is the user-supplied initial estimate. ' ...
    'Tracks shorter than the minimum history length (default: 3 frames) use $D_(rot,prior)$.']);

writeHeading(sel, '3.5 Orientation Innovation Covariance and Cost', 2);

writeBodyAuto(sel, wdoc, ...
    ['The orientation cost mirrors the spatial linking cost by normalizing the squared angular displacement by an innovation covariance [2]. ' ...
    'The orientation innovation covariance $S_' psi_ch '$ combines the process variance (predicted angular spread) ' ...
    'with the measurement variances of both the current track endpoint and the candidate detection:']);

writeEquation(sel, wdoc, ['P_(process)=4D_(rot) ' delta_ch 't']);
writeCodeRef(sel, 'costMat6DSMOLMLink.m:429');

writeEquation(sel, wdoc, ['S_' psi_ch '=P_(process)+R_(curr)+R_(next)']);
writeCodeRef(sel, 'costMat6DSMOLMLink.m:431');

writeBodyAuto(sel, wdoc, ...
    ['Here $R_(curr)$ and $R_(next)$ are the squared measurement uncertainties for the current and candidate orientations, respectively. ' ...
    'When wobble-dependent weighting is enabled, these measurement variances are modulated by the wobble angle $' omega_ch '$ through the order parameter $' gamma_ch '$ [3]: ' ...
    'larger wobble (lower $' gamma_ch '$) increases $R$, reflecting the reduced angular precision of a rapidly wobbling dipole [4]. ' ...
    'The measurement variance is scaled as $R=' sigma_ch '^2/' gamma_ch '^2$, ' ...
    'where $' gamma_ch '$ is derived from $' omega_ch '$ via $' gamma_ch '=1-3' omega_ch '/(4' pi_ch ')+' omega_ch '^2/(8' pi_ch '^2)$. ' ...
    'The orientation cost under each propagation scheme (forward, backward, Brownian) is:']);

writeEquation(sel, wdoc, ['C_(orient,m)=(' delta_ch psi_ch '_m^2)/(S_' psi_ch ')']);
writeCodeRef(sel, 'costMat6DSMOLMLink.m:467-469');

writeBodyAuto(sel, wdoc, ...
    'Level 3 selects the minimum cost across all three propagation schemes:');

writeEquation(sel, wdoc, 'C_(orient)=min(C_(orient,fwd), C_(orient,bwd), C_(orient,brn))');
writeCodeRef(sel, 'costMat6DSMOLMLink.m:472-473  (min over costStack)');

writeBodyAuto(sel, wdoc, ...
    ['The winning scheme index is recorded in the orientPropagationScheme matrix for diagnostic purposes, ' ...
    'allowing post hoc analysis of which motion regime dominates in different regions of the sample.']);

%% ---- 4. COMBINED COST ----
writeHeading(sel, '4. Combined Cost Matrix and LAP Assignment', 1);

writeBodyAuto(sel, wdoc, ...
    ['The total linking cost combines spatial and orientation contributions through user-specified weights, ' ...
    'enabling the LAP solver to simultaneously optimize positional and orientational consistency [1]. ' ...
    'For each valid track-detection pair $(i, j)$ in the linking cost matrix, the per-link cost is:']);

writeEquation(sel, wdoc, ['C(i,j)=w_(spatial)' cdot 'C_(spatial)(i,j)+w_(orient)' cdot 'C_(orient)(i,j)+w_' omega_ch cdot 'C_' omega_ch '(i,j)']);
writeCodeRef(sel, 'costMat6DSMOLMLink.m:505,508');

writeBodyAuto(sel, wdoc, ...
    ['Following the assignment-matrix formalism of Jaqaman et al. [1], frame-to-frame linking is solved by finding the binary assignment matrix ' ...
    '$A$ (with entries $A_(i,j) ' char(8712) ' {0,1}$) that minimizes the total cost over all track-detection pairs:']);

sumSym = char(8721); % ∑
writeEquation(sel, wdoc, ['A' hat '=arg min ' sumSym '_(i=1)^(N_(rows)) ' sumSym '_(j=1)^(N_(cols)) A_(i,j)' cdot 'C(i,j)']);
writeCodeRef(sel, 'lap.m  (Jonker-Volgenant solver, called from u-track3D)');

writeBodyAuto(sel, wdoc, ...
    'subject to the one-to-one assignment constraints:');

writeEquation(sel, wdoc, [sumSym '_(i=1)^(N_(rows)) A_(i,j)=1,    ' sumSym '_(j=1)^(N_(cols)) A_(i,j)=1']);

writeBodyAuto(sel, wdoc, ...
    ['These constraints enforce that each row (track) is matched to exactly one column (detection), and vice versa. ' ...
    'Birth and death dummy entries in the augmented cost matrix allow tracks to start, end, or skip frames. ' ...
    'This $' sumSym sumSym '$ formulation is identical in structure to Eqs. (1)-(2) of Jaqaman et al. [1] ' ...
    'and is solved by the Jonker-Volgenant algorithm [7].']);

writeBodyAuto(sel, wdoc, ...
    ['The weight $w_(spatial)$ (default 1.0) scales the spatial cost, ' ...
    '$w_(orient)$ (default 1.0) scales the orientation cost, ' ...
    'and $w_' omega_ch '$ (default 0.0) scales an optional wobble continuity cost. ' ...
    'The wobble cost $C_' omega_ch '$ penalizes changes in the wobble solid angle $' omega_ch '$ between linked detections. ' ...
    'Only the upper-left block of the cost matrix (valid linking region) receives the orientation augmentation; ' ...
    'the birth, death, and auxiliary blocks remain unmodified from the base u-track3D output [1].']);

writeBodyAuto(sel, wdoc, ...
    ['The augmented cost matrix is solved by the Jonker-Volgenant algorithm [7] to obtain the globally optimal assignment. ' ...
    'This algorithm solves the linear assignment problem in $O(n^3)$ time, ' ...
    'simultaneously minimizing the total spatial and orientational linking cost across all particles, ' ...
    'subject to the constraint that each detection is assigned to at most one track [1]. ' ...
    'Unmatched tracks are terminated (assigned to death dummies) and unmatched detections initiate new tracks (birth dummies). ' ...
    'The key advantage of the additive cost formulation is that orientation information naturally resolves spatial ambiguities: ' ...
    'when two tracks approach the same detection, the orientation cost breaks the tie in favor of the track ' ...
    'with compatible angular coordinates (Figure 2A).']);

writeHeading(sel, '4.1 Gap Closing with Orientation', 2);

writeBodyAuto(sel, wdoc, ...
    ['The second LAP closes gaps between track segments using orientation similarity as additional evidence for segment identity [1]. ' ...
    'When a track segment ends at frame $t_(end)$ and another begins at frame $t_(start)$ (with $t_(start)>t_(end)+1$), ' ...
    'the gap-closing cost combines spatial proximity with angular distance between the endpoint and startpoint orientations. ' ...
    'The angular distance is normalized by the square root of the time gap to account for expected rotational diffusion during the gap interval, ' ...
    'since the mean angular displacement scales as $' sqrt_ch '(4D_(rot)' delta_ch 't)$ under Brownian rotation [5]. ' ...
    'Three scenarios illustrate the value of orientation in gap closing (Figure 2B): ' ...
    '(i) a track gap is correctly closed when the endpoint and startpoint share compatible orientations; ' ...
    '(ii) a gap closure is rejected when orientations mismatch despite spatial proximity; ' ...
    'and (iii) crossing tracks that are spatially ambiguous are correctly resolved by their distinct orientation signatures. ' ...
    'Merge and split events are not currently used in the 6D-SMOLM implementation (mergeSplit = 0), ' ...
    'as individual fluorescent molecules do not undergo aggregation or disaggregation [1].']);

%% ---- 5. PHOTOPHYSICS ----
writeHeading(sel, '5. Fluorophore Photophysics Model', 1);

writeBody(sel, ...
    ['Fluorophore photophysics are modeled as a three-state continuous-time Markov process to generate realistic temporal gaps ' ...
    'that test the gap-closing capability of the tracking algorithm [8,9]. ' ...
    'Each simulated fluorophore occupies one of three states at any time: ' ...
    'emitting (on), dark (off), or permanently photobleached. ' ...
    'State transitions are sampled at each simulation frame as independent Bernoulli trials, ' ...
    'with per-frame transition probabilities derived from the underlying continuous-time rate constants [9,10]:']);

writeEquation(sel, wdoc, ['p_(off)=k_(off)' cdot delta_ch 't']);
writeCodeRef(sel, 'generate6DTrajectories.m:279  (if rand < o.BlinkOffRate)');

writeEquation(sel, wdoc, ['p_(on)=k_(on)' cdot delta_ch 't']);
writeCodeRef(sel, 'generate6DTrajectories.m:283  (if rand < o.BlinkOnRate)');

writeEquation(sel, wdoc, ['p_(bleach)=k_(bleach)' cdot delta_ch 't']);
writeCodeRef(sel, 'generate6DTrajectories.m:272  (if rand < o.BleachRate)');

writeBodyAuto(sel, wdoc, ...
    ['This discrete-time approximation is valid when $k' cdot delta_ch 't' char(8810) '1$, ' ...
    'i.e., when the transition probability per frame is small compared to unity [10]. ' ...
    'The user inputs (BlinkOffRate, BlinkOnRate, BleachRate) are dimensionless probabilities, ' ...
    'already representing the product $k' cdot delta_ch 't$. ' ...
    'The relationship to experimentally measured time constants is: ' ...
    '$BlinkOffRate' approx delta_ch 't/' tau_ch '_(on)$ and $BlinkOnRate' approx delta_ch 't/' tau_ch '_(off)$, ' ...
    'where $' tau_ch '_(on)$ and $' tau_ch '_(off)$ are the mean on-time and off-time dwell times respectively.']);

writeBody(sel, ...
    ['The photophysics state machine is evaluated at each frame in the following order: ' ...
    '(1) if the molecule is bleached, the frame is skipped entirely; ' ...
    '(2) a bleaching check is performed (applicable from both on and dark states); ' ...
    '(3) if the molecule is on, it may transition to dark; if dark, it may transition to on. ' ...
    'When a molecule is in the dark state, it continues to diffuse spatially and rotationally ' ...
    'but does not produce a detection, creating a temporal gap in the trajectory. ' ...
    'When the molecule returns to the emitting state, it reappears at a new position, ' ...
    'and the gap-closing LAP (Section 4.1) must bridge this interval. ' ...
    'Bleached molecules cease all propagation permanently.']);

%% ---- 6. LOCALIZATION NOISE ----
writeHeading(sel, '6. Localization Noise Model', 1);

writeBody(sel, ...
    ['The trajectory simulator injects localization noise directly onto ground-truth coordinates, ' ...
    'bypassing image formation and localization estimation entirely. ' ...
    'This approach isolates the tracking algorithm''s performance from the choice of localization method. ' ...
    'For each emitting detection, the observed coordinates are:']);

writeEquation(sel, wdoc, ['x_(obs)=x+' sigma_ch '_(xy)' cdot 'n,    n~N(0,1)']);
writeCodeRef(sel, 'generate6DTrajectories.m:435-436  (x_obs, y_obs)');

writeEquation(sel, wdoc, [theta '_(obs)=' theta '+' sigma_ch '_' theta cdot 'n']);
writeCodeRef(sel, 'generate6DTrajectories.m:438  (theta_obs)');

writeBodyAuto(sel, wdoc, ...
    ['Here $' sigma_ch '_(xy)$ is the lateral localization precision (default: 20 nm) ' ...
    'and $' sigma_ch '_' theta '$ is the angular localization precision (default: 5' char(176) '). ' ...
    'Separate noise parameters exist for axial position ($' sigma_ch '_z$, default: 50 nm), ' ...
    'azimuthal angle ($' sigma_ch '_' phi_ch '$, default: 5' char(176) '), ' ...
    'and wobble ($' sigma_ch '_' gamma_ch '$, default: 0.05). ' ...
    'Each noise term is drawn independently from a zero-mean Gaussian distribution, ' ...
    'and the observed value is clamped to physically valid bounds ' ...
    '(e.g., $' theta '_(obs)' char(8712) '[0' char(176) ', 90' char(176) ']$).']);

writeBodyAuto(sel, wdoc, ...
    ['In a real experiment, localization precision depends on the number of detected photons $N$ ' ...
    'through the Cramer-Rao lower bound: $' sigma_ch '_(xy)' approx sigma_ch '_(PSF)/' sqrt_ch 'N$ [4]. ' ...
    'The simulator does not enforce this relationship; the signal photon count and localization noise ' ...
    'are independent user inputs. ' ...
    'We evaluate tracking performance across a range of localization precisions, ' ...
    'corresponding to experimental conditions spanning low to high signal-to-noise ratio:']);

% Table description
writeBodyAuto(sel, wdoc, ...
    ['Low precision: $' sigma_ch '_(xy)=50$ nm, $' sigma_ch '_' theta '=15' char(176) '$ (dim molecule / high background). ' ...
    'Medium precision: $' sigma_ch '_(xy)=20$ nm, $' sigma_ch '_' theta '=5' char(176) '$ (typical SM experiment). ' ...
    'High precision: $' sigma_ch '_(xy)=10$ nm, $' sigma_ch '_' theta '=2' char(176) '$ (bright emitter / low background).']);

%% ---- FIGURE 2 ----
writeHeading(sel, 'Figure 2', 1);

sel.Style = 'Normal';
sel.Font.Name = 'Arial';
sel.Font.Size = 10;
sel.Font.Italic = true;
sel.ParagraphFormat.Alignment = 1;
sel.TypeText('[INSERT FIGURE 2 PANELS A AND B HERE]');
sel.TypeParagraph;

sel.Font.Italic = false;
sel.ParagraphFormat.Alignment = 0;
sel.Font.Size = 10;
writeBody(sel, ...
    ['Figure 2. Orientation-augmented linear assignment problems for 6D-SMOLM tracking. ' ...
    '(A) Frame-to-frame linking (LAP 1). Three particles (A, B, C) in frame t are linked to detections in frame t+1. ' ...
    'Colored arrows at each detection represent the measured dipole orientation (' theta ', ' phi_ch '). ' ...
    'Solid colored lines indicate optimal 6D assignments; dashed black lines indicate rejected candidate links. ' ...
    'Orientation similarity between matched pairs (e.g., A to A'') reduces the total cost below that of spatially similar ' ...
    'but orientationally incompatible alternatives. ' ...
    '(B) Gap closing and segment linking (LAP 2) via orientational coordinates. ' ...
    'Three scenarios are shown: (i) correct gap closing when the segment endpoint and startpoint share a low-cost orientation match; ' ...
    '(ii) rejection of a segment link due to (' theta ', ' phi_ch ') mismatch despite spatial continuity; ' ...
    'and (iii) disambiguation of crossing trajectories where high spatial costs alone are insufficient, ' ...
    'but distinct orientation signatures correctly assign detections to the appropriate track segments.']);

%% ---- APPENDIX ----
writeHeading(sel, 'Appendix: Rotational Brownian Step on the Unit Sphere', 1);

writeBody(sel, ...
    ['This appendix illustrates the geometric construction underlying the rotational Brownian step on S' sup2 ' ' ...
    'used in the trajectory generator (generate6DTrajectories.m, lines 619-632) and assumed by the orientation Kalman cost (Section 3.2). ' ...
    'The four panels (Figure A1) walk through the steps of one Brownian rotation increment.']);

% Insert figure
appendixFig = fullfile(pwd, 'tangent_plane_viz.png');
if exist(appendixFig, 'file')
    sel.Style = 'Normal';
    sel.ParagraphFormat.Alignment = 1;
    sel.ParagraphFormat.SpaceAfter = 6;
    inlineShape = sel.InlineShapes.AddPicture(appendixFig);
    % Resize to ~6 inches wide preserving aspect
    inlineShape.LockAspectRatio = -1;
    inlineShape.Width = 432; % 6 inches in points
    sel.TypeParagraph;
else
    writeBody(sel, '[FIGURE A1: tangent_plane_viz.png not found]');
end

% Caption
sel.Style = 'Normal';
sel.Font.Name = 'Times New Roman';
sel.Font.Size = 10;
sel.Font.Italic = false;
sel.Font.Bold = false;
sel.Font.set('Color', 0);
sel.ParagraphFormat.Alignment = 0;
sel.ParagraphFormat.SpaceAfter = 8;
sel.TypeText(['Figure A1. Rotational Brownian step on the unit sphere. ' ...
    '(A) The dipole orientation ' char(956) ' (blue arrow) lies on the unit sphere S' sup2 '. ' ...
    'The orange tangent plane touches S' sup2 ' only at ' char(956) ' and is everywhere perpendicular to ' char(956) '. ' ...
    'Because ' char(956) ' is constrained to unit length, any infinitesimal motion must lie within this plane. ' ...
    '(B) Two orthogonal unit vectors e' char(8321) ' (red) and e' char(8322) ' (green) span the tangent plane at ' char(956) '. ' ...
    'They are constructed to be perpendicular to ' char(956) ' and to each other, providing two independent local directions ' ...
    'in which the orientation can diffuse. ' ...
    '(C) Two independent Gaussian samples a' char(8321) ', a' char(8322) ' ~ N(0, 2D_(rot)' char(916) 't) are drawn in the tangent plane ' ...
    '(gray dots show many such samples). One specific displacement ' char(948) ' = a' char(8321) 'e' char(8321) ' + a' char(8322) 'e' char(8322) ' ' ...
    '(magenta arrow) is the net infinitesimal step. The squared magnitude has expectation E[|' char(948) '|' sup2 '] = 4D_(rot)' char(916) 't, ' ...
    'reflecting the two tangent-plane degrees of freedom. ' ...
    '(D) The new orientation ' char(956) '_(new) (purple) is obtained by rotating ' char(956) ' by angle |' char(948) '| about an axis perpendicular to ' char(948) ' ' ...
    'via the Rodrigues formula. The red arc traces the great-circle path on S' sup2 ', so ' char(956) '_(new) lands exactly back on the unit sphere, ' ...
    'preserving |' char(956) '| = 1. This is the operation implemented by rotateVector / rodrigues_rotate.']);
sel.TypeParagraph;

%% ---- REFERENCES ----
writeHeading(sel, 'References', 1);

writeRef(sel, 1, ['Jaqaman, K., Loerke, D., Mettlen, M., Hainaut, P., Riche, S., Jaqaman, K., ' ...
    'Jain, A., et al. Robust single-particle tracking in live-cell time-lapse sequences. ' ...
    'Nature Methods 5(8), 695-702 (2008).']);

writeRef(sel, 2, ['Kalman, R.E. A new approach to linear filtering and prediction problems. ' ...
    'Journal of Basic Engineering 82(1), 35-45 (1960).']);

writeRef(sel, 3, ['Fourkas, J.T. Rapid determination of the three-dimensional orientation of single molecules. ' ...
    'Optics Letters 26(4), 211-213 (2001).']);

writeRef(sel, 4, ['Zhang, O., Lu, J., Ding, T., & Bhatt, R. Imaging the three-dimensional orientation and rotational ' ...
    'mobility of fluorescent emitters using the Tri-spot point spread function. ' ...
    'Applied Physics Letters 113, 031103 (2018).']);

writeRef(sel, 5, ['Hofling, F. & Straube, A.V. Rotational Brownian motion: trajectory, orientation dynamics, ' ...
    'and geometric integration. Physical Review Research 7, 043034 (2025).']);

writeRef(sel, 6, ['Berglund, A.J. Statistics of camera-based single-particle tracking. ' ...
    'Physical Review E 82, 011917 (2010).']);

writeRef(sel, 7, ['Jonker, R. & Volgenant, A. A shortest augmenting path algorithm for dense and sparse ' ...
    'linear assignment problems. Computing 38, 325-340 (1987).']);

writeRef(sel, 8, ['Lee, S.H., Shin, J.Y., Lee, A. & Bustamante, C. Counting single photoactivatable ' ...
    'fluorescent molecules by photoactivated localization microscopy (PALM). ' ...
    'Proceedings of the National Academy of Sciences 109(43), 17436-17441 (2012).']);

writeRef(sel, 9, ['Linden, M., Chmyrov, V., Bhatt, D.K., Bhatt, R., et al. ' ...
    'Single molecule imaging simulations with advanced fluorophore photophysics. ' ...
    'Communications Biology 6, 56 (2023).']);

writeRef(sel, 10, ['Gillespie, D.T. Perspective: Stochastic algorithms for chemical kinetics. ' ...
    'Journal of Chemical Physics 138, 170901 (2013).']);

writeRef(sel, 11, ['Michalet, X. Mean square displacement analysis of single-particle trajectories with localization error: ' ...
    'Brownian motion in an isotropic medium. Physical Review E 82, 041914 (2010).']);

%% ---- Save and close ----
wdoc.SaveAs2(outputFileWin);

% Now reopen and BuildUp all equations
wdoc.Close(false);
pause(5);  % Allow Word and OneDrive to finish

for attempt = 1:3
    try
        wdoc2 = word.Documents.Open(outputFileWin);
        break;
    catch
        fprintf('  Reopen attempt %d failed, retrying...\n', attempt);
        pause(5);
    end
end
nEq = wdoc2.OMaths.Count;
fprintf('Found %d OMath equations. Building up...\n', nEq);
for i = 1:nEq
    try
        wdoc2.OMaths.Item(i).BuildUp;
    catch ME
        fprintf('  BuildUp eq %d: %s\n', i, ME.message);
    end
end
wdoc2.Save;
wdoc2.Close(false);

word.Quit;
delete(word);

% Copy from temp to final OneDrive location
pause(2);
if exist(finalFile, 'file')
    delete(finalFile);
    pause(1);
end
copyfile(outputFileWin, finalFile, 'f');
fprintf('Document saved to: %s\n', finalFile);
fprintf('Open in Word to:\n');
fprintf('  1. Insert Figure 2 panels where indicated\n');
fprintf('  2. Verify equation rendering\n');
